import Head from 'next/head';

import { Approaching } from '../components/Approaching';
import { Contact } from '../components/Contact';
import { Depoiments } from '../components/Depoiments';
import { Faq } from '../components/FAQ';
import { Modality } from '../components/Modality';
import { Services } from '../components/Services';
import { WhoAmI } from '../components/WhoAmI';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sandy Carvalho | Psicóloga Sistêmica</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="container">
        <WhoAmI />
      </main>
      <Approaching />
      <div className="container" id="modalidades">
        <Modality />
      </div>
      <Services />
      <div className="container" id="duvidas">
        <Faq />
      </div>
      <Depoiments />
      <Contact />
    </div>
  );
}
